import { Profile } from './types';

export const SPECIALTIES = [
  'Software Engineering',
  'AI & Machine Learning',
  'UX Design',
  'Product Management',
  'Data Science & Analytics',
];

export const MOCK_MENTORS: Profile[] = [
  {
    id: 'm1',
    name: 'Dr. Evelyn Chen',
    email: 'evelyn.chen@google.com',
    role: 'mentor',
    specialty: 'AI & Machine Learning',
    bio: 'Principal AI Researcher with 8+ years of experience leading neural network design, computer vision, and LLM development. Passionate about helping students kickstart high-impact AI careers.',
    skills: ['PyTorch', 'Large Language Models', 'Deep Learning', 'Python', 'MLOps'],
    company: 'Google',
    experience: 8,
    hourlyRate: 120,
    rating: 4.9,
    reviewCount: 42,
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    availability: [
      { id: 'a1', dayOfWeek: 1, startTime: '15:00', endTime: '16:00', timezone: 'UTC', label: 'Monday 3:00 PM' },
      { id: 'a2', dayOfWeek: 3, startTime: '10:00', endTime: '11:00', timezone: 'UTC', label: 'Wednesday 10:00 AM' },
      { id: 'a3', dayOfWeek: 5, startTime: '16:00', endTime: '17:00', timezone: 'UTC', label: 'Friday 4:00 PM' },
    ],
  },
  {
    id: 'm2',
    name: 'Marcus Vance',
    email: 'marcus.vance@apple.com',
    role: 'mentor',
    specialty: 'UX Design',
    bio: 'Senior UX Design Director specialized in sleek minimalist interface design, design systems, and user behavior psychology. Let us refine your portfolio and build experiences users adore.',
    skills: ['Figma', 'Design Systems', 'Interactive Prototypes', 'User Research', 'Typography'],
    company: 'Apple',
    experience: 12,
    hourlyRate: 150,
    rating: 5.0,
    reviewCount: 61,
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    availability: [
      { id: 'a4', dayOfWeek: 2, startTime: '14:00', endTime: '15:00', timezone: 'UTC', label: 'Tuesday 2:00 PM' },
      { id: 'a5', dayOfWeek: 4, startTime: '11:00', endTime: '12:00', timezone: 'UTC', label: 'Thursday 11:00 AM' },
      { id: 'a6', dayOfWeek: 5, startTime: '13:00', endTime: '14:00', timezone: 'UTC', label: 'Friday 1:00 PM' },
    ],
  },
  {
    id: 'm3',
    name: 'Sarah Jenkins',
    email: 'sarah.j@stripe.com',
    role: 'mentor',
    specialty: 'Product Management',
    bio: 'Lead PM at Stripe overseeing developer platforms. Expert in product-led growth, agile methodologies, strategy, and roadmap execution. I will help you ace your PM casing interviews.',
    skills: ['Product Strategy', 'Growth Marketing', 'A/B Testing', 'Roadmapping', 'Agile'],
    company: 'Stripe',
    experience: 6,
    hourlyRate: 110,
    rating: 4.8,
    reviewCount: 29,
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200',
    availability: [
      { id: 'a7', dayOfWeek: 1, startTime: '09:00', endTime: '10:00', timezone: 'UTC', label: 'Monday 9:00 AM' },
      { id: 'a8', dayOfWeek: 2, startTime: '16:00', endTime: '17:00', timezone: 'UTC', label: 'Tuesday 4:00 PM' },
      { id: 'a9', dayOfWeek: 3, startTime: '14:00', endTime: '15:00', timezone: 'UTC', label: 'Wednesday 2:00 PM' },
    ],
  },
  {
    id: 'm4',
    name: 'Devon Miller',
    email: 'devon.miller@netflix.com',
    role: 'mentor',
    specialty: 'Software Engineering',
    bio: 'Staff Engineer at Netflix focused on high-throughput backend infrastructure, Node.js concurrency, and distributed datastores. I can help you prep for systems architecture interviews.',
    skills: ['Node.js', 'Distributed Systems', 'Redis', 'AWS', 'System Design'],
    company: 'Netflix',
    experience: 10,
    hourlyRate: 130,
    rating: 4.9,
    reviewCount: 55,
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=200',
    availability: [
      { id: 'a10', dayOfWeek: 3, startTime: '15:00', endTime: '16:00', timezone: 'UTC', label: 'Wednesday 3:00 PM' },
      { id: 'a11', dayOfWeek: 4, startTime: '15:00', endTime: '16:00', timezone: 'UTC', label: 'Thursday 3:00 PM' },
      { id: 'a12', dayOfWeek: 6, startTime: '10:00', endTime: '11:00', timezone: 'UTC', label: 'Saturday 10:00 AM' },
    ],
  },
  {
    id: 'm5',
    name: 'Aiko Tanaka',
    email: 'aiko.tanaka@figma.com',
    role: 'mentor',
    specialty: 'Software Engineering',
    bio: 'Senior Full-Stack Engineer and Manager. I love simplifying React architecture, CSS layouts, and helping career switchers secure their first remote roles in tech.',
    skills: ['React', 'TypeScript', 'Tailwind CSS', 'Next.js', 'GraphQL'],
    company: 'Figma',
    experience: 7,
    hourlyRate: 95,
    rating: 4.9,
    reviewCount: 38,
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    availability: [
      { id: 'a13', dayOfWeek: 2, startTime: '10:00', endTime: '11:00', timezone: 'UTC', label: 'Tuesday 10:00 AM' },
      { id: 'a14', dayOfWeek: 4, startTime: '13:00', endTime: '14:00', timezone: 'UTC', label: 'Thursday 1:00 PM' },
      { id: 'a15', dayOfWeek: 5, startTime: '10:00', endTime: '11:00', timezone: 'UTC', label: 'Friday 10:00 AM' },
    ],
  },
];
